# Generated by Django 3.2.9 on 2022-01-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('InventoryEquipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreLocation',
            fields=[
                ('street_address', models.CharField(max_length=50, verbose_name='The Street Address')),
                ('zipcode', models.CharField(max_length=10, verbose_name='Zip Code Of the Location')),
                ('state', models.CharField(max_length=50, verbose_name='State of this location')),
                ('city', models.CharField(max_length=30, verbose_name='City of this location')),
                ('Address', models.CharField(max_length=50, verbose_name='Address of the location')),
                ('Name', models.CharField(max_length=50, verbose_name='Common name for the store')),
                ('StoreID', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='The ID of this store')),
                ('Equipment', models.ManyToManyField(to='InventoryEquipment.Equipment', verbose_name='Types of equipment this store keeps in stock')),
            ],
        ),
    ]
