# Generated by Django 3.2.9 on 2022-01-10 21:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryEquipment', '0005_auto_20220110_1633'),
        ('InventoryStores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('receipt', models.TextField(verbose_name='Receipt Data')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_of_sale', models.DateTimeField(verbose_name='The time of the sale')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryEquipment.equipment', verbose_name='Type of Equipment Sold')),
                ('equipment_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EquipmentInstance', to='InventoryEquipment.equipmentinstance', verbose_name='The exact equipment sold')),
                ('store_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryStores.storelocation', verbose_name='')),
            ],
        ),
    ]
