# Generated by Django 3.2.9 on 2022-01-10 19:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description of the equipment')),
                ('manufacturer', models.CharField(max_length=50, verbose_name='Who Makes this equipment?')),
                ('model', models.CharField(max_length=50, verbose_name='Model of this equipment')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=50, verbose_name='Serial Number for this equipment')),
                ('isSold', models.BooleanField(default=False)),
                ('arrived_date', models.DateField(verbose_name='Date the product was received')),
                ('last_transaction_date', models.DateField(auto_now_add=True, verbose_name='Date information was last modified')),
                ('location_status', models.CharField(max_length=50, verbose_name='Location Status Of Equipment')),
                ('equipment_status', models.CharField(max_length=50, verbose_name='Equipment Status active/inactive/etc')),
                ('current_customer_id', models.CharField(max_length=50, verbose_name='Customer ID of the customer who currently has possession of equipment')),
                ('meter_hours', models.PositiveIntegerField(null=True, verbose_name='Meter hours on the equipment')),
                ('next_pm_date', models.DateField(verbose_name='Date for next maintenance')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('receipt', models.TextField(verbose_name='Receipt Data')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_of_sale', models.DateTimeField(verbose_name='The time of the sale')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryEquipment.equipment', verbose_name='Type of Equipment Sold')),
                ('equipment_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EquipmentInstance', to='InventoryEquipment.equipmentinstance', verbose_name='The exact equipment sold')),
            ],
        ),
    ]
