# Generated by Django 3.2.9 on 2022-01-10 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('InventoryStores', '0001_initial'),
        ('InventoryEquipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='store_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryStores.storelocation', verbose_name=''),
        ),
        migrations.AddField(
            model_name='equipmentinstance',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryEquipment.equipment', verbose_name='Which type of equipment is this'),
        ),
    ]
