# Generated by Django 3.2.9 on 2022-01-10 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('InventoryStores', '0001_initial'),
        ('InventoryEquipment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentinstance',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Manager responsible for this equipment'),
        ),
        migrations.AddField(
            model_name='equipmentinstance',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='InventoryEquipment.sale', verbose_name='The Sale Data for when this was sold'),
        ),
        migrations.AddField(
            model_name='equipmentinstance',
            name='store_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryStores.storelocation', verbose_name='Location Equipment was delivered to'),
        ),
    ]
