# Generated by Django 3.2.9 on 2022-01-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryEquipment', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentinstance',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=''),
        ),
    ]
