# Generated by Django 3.2.9 on 2022-01-10 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryEquipment', '0004_equipmentinstance_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='equipment_instance',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='store_location',
        ),
        migrations.RemoveField(
            model_name='equipmentinstance',
            name='model',
        ),
    ]
