# Generated by Django 3.2.9 on 2022-01-12 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('InventoryStores', '0002_sale'),
        ('InventoryEquipment', '0007_auto_20220112_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='current_customer_id',
            field=models.CharField(default=0, max_length=50, verbose_name='Customer ID of the customer who currently has possession of equipment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True, verbose_name='When was this Transaction Approved?'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='date_submitted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='When was this Transaction Submitted?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='equipment_status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=2, verbose_name='Equipment Status active/inactive/etc'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='location_status',
            field=models.CharField(choices=[('OH', 'On Hand'), ('PT', 'Patient'), ('RC', 'Repair Center'), ('RT', 'Retired'), ('MIA', 'Missing In Action')], default='OH', max_length=3, verbose_name='Location Status Of Equipment'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='InventoryUsers.customuser', verbose_name='Manager responsible for this equipment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='meter_hours',
            field=models.PositiveIntegerField(null=True, verbose_name='Meter hours on the equipment'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='next_pm_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date for next maintenance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='serial_number',
            field=models.CharField(default=0, max_length=50, verbose_name='Serial Number for the associated Equipment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='store_location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='InventoryStores.storelocation', verbose_name='Location Equipment was delivered to'),
            preserve_default=False,
        ),
    ]
