# Generated by Django 3.2.9 on 2022-01-12 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryEquipment', '0008_auto_20220112_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='equipment_instance',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='serial_number',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='InventoryEquipment.equipmentinstance', verbose_name='The equipment that this transaction is for'),
        ),
    ]
