# Generated by Django 3.2.9 on 2022-01-12 23:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryStores', '0002_sale'),
        ('InventoryEquipment', '0009_auto_20220112_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='store_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryStores.storelocation', verbose_name='Location Equipment is currently at'),
        ),
    ]
