# Generated by Django 3.2.9 on 2022-01-13 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryStores', '0002_sale'),
        ('InventoryUsers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='home_store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='InventoryStores.storelocation', verbose_name='The store that this user works at'),
            preserve_default=False,
        ),
    ]
